# Generated by Django 5.2.6 on 2025-10-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_comment_options_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
